# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9bbb880ee5aa8e113fb3e9325d087c2d61c7baf08a189f1d2ac6b3996cbdad37bf435264a52f0e607b83f8fb2b71e4e93e51008a86b9510d0c1f652ff3d572

test:
  secret_key_base: d49a9cccede3a8547f2b969b971067777a47d1b6bafdbaaa9702d2bd2b6d37a3e4fc9f86875a8c53991b0a9ae4b9252d242d03492f02f52a0c118fbe74b91f96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
